# -*- coding: utf-8 -*-
"""Calculator in Python (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvIDJUuThQkbzozrKH9X9rHnEJM07cLt
"""

import tkinter as tk

window = tk.Tk()
window.geometry("500x320")
window.title("P01 - Simple Calculator by Harshal Dahivalikar | 25-05-2025 ")

calculation = ""

def add_to_calculation(symbol):
    global calculation
    calculation += str(symbol)
    text_result.delete(1.0, "end" )
    text_result.insert(1.0, calculation)

def evaluate_calculation():
    global calculation
    try:
        calculation = str(eval(calculation))
        text_result.delete(1.0,"end")
        text_result.insert(1.0, calculation)
    except:
        clear_field()
        text_result.insert(1.0, "Error")
        pass

def clear_field():
    global calculation
    calculation = ""
    text_result.delete(1.0, "end")
    pass

text_result = tk.Text(window, height=2, width=28, font=("Helvetica", 23))
text_result.grid(columnspan=5)
btn_1 = tk.Button(window , text = "1", command = lambda: add_to_calculation(1), width = 5, font = ("Helvetica", 18))
btn_1.grid(row = 1, column = 1)
btn_2 = tk.Button(window , text = "2", command = lambda: add_to_calculation(2), width = 5, font = ("Helvetica", 18))
btn_2.grid(row = 1, column = 2)
btn_3 = tk.Button(window , text = "3", command = lambda: add_to_calculation(3), width = 5, font = ("Helvetica", 18))
btn_3.grid(row = 1, column = 3)
btn_4 = tk.Button(window , text = "4", command = lambda: add_to_calculation(4), width = 5, font = ("Helvetica", 18))
btn_4.grid(row = 2, column = 1)
btn_5 = tk.Button(window , text = "5", command = lambda: add_to_calculation(5), width = 5, font = ("Helvetica", 18))
btn_5.grid(row = 2, column = 2)
btn_6 = tk.Button(window , text = "6", command = lambda: add_to_calculation(6), width = 5, font = ("Helvetica", 18))
btn_6.grid(row = 2, column = 3)
btn_7 = tk.Button(window , text = "7", command = lambda: add_to_calculation(7), width = 5, font = ("Helvetica", 18))
btn_7.grid(row = 3, column = 1)
btn_8 = tk.Button(window , text = "8", command = lambda: add_to_calculation(8), width = 5, font = ("Helvetica", 18))
btn_8.grid(row = 3, column = 2)
btn_9 = tk.Button(window , text = "9", command = lambda: add_to_calculation(9), width = 5, font = ("Helvetica", 18))
btn_9.grid(row = 3, column = 3)
btn_0 = tk.Button(window , text = "0", command = lambda: add_to_calculation(0), width = 5, font = ("Helvetica", 18))
btn_0.grid(row = 4, column = 2)
btn_plus = tk.Button(window , text = "+", command = lambda: add_to_calculation("+"), width = 5, font = ("Helvetica", 18))
btn_plus.grid(row = 1, column = 4)
btn_multi = tk.Button(window , text = "x", command = lambda: add_to_calculation("*"), width = 5, font = ("Helvetica", 18))
btn_multi.grid(row = 2, column = 4)
btn_sub = tk.Button(window , text = "-", command = lambda: add_to_calculation("-"), width = 5, font = ("Helvetica", 18))
btn_sub.grid(row = 3, column = 4)
btn_div = tk.Button(window , text = "/", command = lambda: add_to_calculation("/"), width = 5, font = ("Helvetica", 18))
btn_div.grid(row = 4, column = 4)
btn_open = tk.Button(window , text = "(", command = lambda: add_to_calculation("("), width = 5, font = ("Helvetica", 18))
btn_open.grid(row = 4, column = 1)
btn_close = tk.Button(window , text = ")", command = lambda: add_to_calculation(")"), width = 5, font = ("Helvetica", 18))
btn_close.grid(row = 4, column = 3)
btn_equals = tk.Button(window , text = "=", command = evaluate_calculation , width = 13, font = ("Helvetica", 18))
btn_equals.grid(row = 5, column = 3, columnspan = 2)
btn_clear = tk.Button(window , text = "C", command = clear_field, width = 13, font = ("Helvetica", 18))
btn_clear.grid(row = 5, column = 1, columnspan = 2)
window.mainloop()

